# Generated by Django 6.0.5 on 2026-05-30 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Policiamento')),
                ('horario_inicio', models.TimeField(verbose_name='Hora Início')),
                ('horario_fim', models.TimeField(verbose_name='Hora Fim')),
            ],
        ),
        migrations.CreateModel(
            name='Policial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_guerra', models.CharField(max_length=100, verbose_name='Nome de Guerra (Ex: Cb José)')),
                ('categoria', models.CharField(choices=[('SD_CB', 'Soldado / Cabo'), ('SGT_SUB', 'Sargento / Subtenente'), ('OFI', 'Oficiais')], max_length=10, verbose_name='Categoria para Pagamento')),
            ],
            options={
                'ordering': ['nome_guerra'],
            },
        ),
        migrations.CreateModel(
            name='PontoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Ponto Fixo')),
                ('localizacao', models.CharField(max_length=255, verbose_name='Endereço/Localização')),
            ],
        ),
        migrations.CreateModel(
            name='ValorHoraCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('SD_CB', 'Soldado / Cabo'), ('SGT_SUB', 'Sargento / Subtenente'), ('OFI', 'Oficiais')], max_length=10, unique=True, verbose_name='Categoria')),
                ('valor_por_hora', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor por Hora (R$)')),
            ],
        ),
        migrations.CreateModel(
            name='CartaoPoliciamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='policiamento.escaladiaria')),
                ('comandante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='como_comandante', to='policiamento.policial')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='como_motorista', to='policiamento.policial')),
                ('patrulheiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='como_patrulheiro', to='policiamento.policial')),
                ('ponto_fixo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policiamento.pontofixo', verbose_name='Ponto Fixo')),
            ],
        ),
    ]
