# Generated by Django 6.0.5 on 2026-06-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policiamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontofixo',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Orientação para a Guarnição'),
        ),
    ]
